version: '3.8'

services:

  app:
    container_name: RestoMenu
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgresql://postgres:d4rk4ng3l@db:5432/restomenu?schema=public"
    networks:
      - db-network

networks:
  db-network:
    external: true
    name: db-network